name: rpiclient_build_checker

on:
  push:
    branches: [ master ]
    paths:
      - 'rpiclient/**'
      - '.github/workflows/rpiclient_build_checker.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'rpiclient/**'
      - '.github/workflows/rpiclient_build_checker.yml'

jobs:
  build:
    name: Build rpiclient
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtool-bin intltool libgtk-3-dev sqlite3 libsqlite3-dev

      - name: Autogen Build System
        run: |
          cd rpiclient
          ./autogen.sh

      - name: Compile Application
        run: |
          cd rpiclient
          make
